bpf: nodeport return with multiple ifaces
projectcalico/felix pull request #2549
Opened 2020-10-29 17:28 UTC by tomastigera

In environments like EKS, where the egress route is determined by the
source IP as well, the return VXLAN packet for the nodeport tunnel may
end up at a wrong interface (and route) because the packet has the
source IP of the backing pod - to avoid being dropped by RPF check etc.

This fix uses the knowledge of the iface where the nodeport ingress
packets came from (recorded for the purpose of RPF check) and send the
packet out straight to the same interface.

Until we get bpf_redirect_neigh() in our supported kernels (5.10+) we
need to maintain an ARP lookup cache that allows us to patch in the
right MAC addresses so that the packet, once forwarded by the host
interface, can reach the next hop.

Each time we see an incoming VXLAN packet for the nodeport tunnel, we
record the IP it came from and the src/dst MAC addresses. We can use the
tunnel IP where we are sending the egress packet to look up the MAC
addresses we should patch in.

The lookup map is an LRU hash with 10k entries. That allows 10k other
nodes to forward their nodeports to a node.

## Description

## Todos
- [ ] Unit tests (full coverage)
- [ ] Integration tests (delete as appropriate) In plan/Not needed/Done
- [ ] Documentation
- [ ] Backport
- [ ] Release note

## Release Note

```release-note
None required
```

2020-11-07 13:08 UTC, seh commented on dataplane/linux/bpf_arp_mgr.go
> +			// and we do not want to overfill the table in a large cluster. If we through
s/through/throw/

2020-11-11 11:19 UTC, fasaxc requested changes
Seems like a pragmatic fix

2020-11-11 11:21 UTC, fasaxc approved these changes
Realised all my comments were in the file you deleted so I guess this is approved :-)

2020-11-11 16:01 UTC, merged

2020-11-11 20:24 UTC, caseydavenport commented
Reminder that this will need cherry-picking if you'd like this to make it to v3.17 :) 

@tomastigera