Replace lib/v3 package with projectcalico/api
projectcalico/felix pull request #2847
Opened 2021-06-17 15:32 UTC by song-jiang

## Description

## Todos
- [ ] Unit tests (full coverage)
- [ ] Integration tests (delete as appropriate) In plan/Not needed/Done
- [ ] Documentation
- [ ] Backport
- [ ] Release note

## Release Note

```release-note
None required
```

2021-06-17 15:46 UTC, neiljerram requested changes
Looking good.  Just wondering:

- why not keep "apiv3" as the package alias, in some files where it doesn't look necessary to change it?

- why are we still getting some API structs from libcalico-go ?

2021-06-17 15:46 UTC, neiljerram commented on calc/l3_route_resolver.go
> +	libapi "github.com/projectcalico/libcalico-go/lib/apis/v3"
Why not keep "apiv3" here?

2021-06-17 15:46 UTC, neiljerram commented on calc/vxlan_resolver.go
> +	libapi "github.com/projectcalico/libcalico-go/lib/apis/v3"
Why not keep "apiv3" here?

2021-06-17 15:46 UTC, neiljerram commented on fv/infrastructure/infra_etcd.go
> +	felixNode := libapi.NewNode()
Why isn't NewNode also moving into the new API repo?

2021-06-17 15:46 UTC, neiljerram commented on fv/infrastructure/infra_etcd.go
> +	felixNode := libapi.NewNode()
(And similarly for other items in this file.)

2021-06-17 15:46 UTC, neiljerram commented on fv/infrastructure/infra_k8s.go
> +func (kds *K8sDatastoreInfra) AddWorkload(wep *libapi.WorkloadEndpoint) (*libapi.WorkloadEndpoint, error) {
Same question as in infra_etcd

2021-06-17 15:46 UTC, neiljerram commented on fv/infrastructure/infrastructure.go
> +	AddWorkload(wep *libapi.WorkloadEndpoint) (*libapi.WorkloadEndpoint, error)
Same question again here.

2021-06-17 16:01 UTC, song-jiang commented
> why are we still getting some API structs from libcalico-go ?
`projectcalico/api/pkg/apis` is the place for public facing API structures (NetworkPolicy, BGPPeer etc.)

`libcalico-go/lib/apis` defines internal API structures (IpamBlock, Node, WorkloadEndpoint etc.) 

I generally use `api` `apiv3` to name public ones , based on if original files has `api` or `apiv3`, and use `libapi` `libapi3` for internal ones. 

> * hy not keep "apiv3" as the package alias, in some files where it doesn't look necessary to change it

Yes. I will fix those files. Think it was done by a batch update.

2021-06-18 09:50 UTC, neiljerram requested changes
So in the files where you now have "libapiv3", I think it would be better to have "apiv3" (as it was before), so that most of the file does not need to change.  I don't think we have a strong precedent for consistency in package alias naming, and I think it's more important to reduce the chance of merge conflicts.

2021-06-18 09:50 UTC, neiljerram commented on calc/l3_route_resolver.go
> +	libapiv3 "github.com/projectcalico/libcalico-go/lib/apis/v3"
I think this should be "apiv3", same as it was before in this file, so that no changes are needed after this point.

2021-06-18 09:50 UTC, neiljerram commented on calc/states_for_test.go
> +	libapiv3 "github.com/projectcalico/libcalico-go/lib/apis/v3"
I think this should be "apiv3", same as it was before in this file, so that no changes are needed after this point.

2021-06-18 10:22 UTC, song-jiang commented on go.mod
> +	github.com/projectcalico/libcalico-go => github.com/song-jiang/libcalico-go v1.6.1-0.20210616135015-6880d0c7bd42
I'll update my PR once libcalico-go changes has been merged.

2021-06-18 10:31 UTC, neiljerram approved these changes
LGTM

2021-06-18 14:09 UTC, merged