WIP: Add ServiceIndex component
projectcalico/felix pull request #2874
Opened 2021-06-28 19:18 UTC by caseydavenport

## Description

## Todos
- [ ] Unit tests (full coverage)
- [ ] Integration tests (delete as appropriate) In plan/Not needed/Done
- [ ] Documentation
- [ ] Backport
- [ ] Release note

## Release Note

```release-note
None required
```

2021-06-30 22:28 UTC, caseydavenport commented
>   It looks like that the field DstIpPortSetIds is a new addition to the proto.Rule struct. Please check if it affects XDP optimizations in any way, update the isValidRuleForXDP function and the "invalid policies" unit test if needed, and then add the name to the knownProtoRuleFields slice above. Please DO NOT blindly add the field to the slice without checking its influence on the XDP optimization.

I know what the test output tells me to do... but I'm wondering if maybe I should just blindly add the field to the slice without checking its influence on the XDP optimization? :thinking:

2021-07-01 10:28 UTC, fasaxc requested changes
Looking great.  Think there are still a few TODOs:

- UTs (including some calc graph FVs for the new service index)
- FVs: should be able to mark those with BPF-SAFE too so that they run in both suites.
- Windows

2021-07-01 10:28 UTC, fasaxc commented on serviceindex/serviceindex.go
> +// updates for endpoints and profiles and passes them through to the Update/DeleteXXX methods.
Copy-pasta

2021-07-01 10:28 UTC, fasaxc commented on serviceindex/serviceindex.go
> +	oldIPSetContributions := idx.membersFromEndpointSlice(cached)
Push this expensive op inside the active check below?

2021-07-01 10:28 UTC, fasaxc commented on serviceindex/serviceindex.go
> +		// we should end a membership removal from the data plane.
typo: end

2021-07-01 10:28 UTC, fasaxc commented on serviceindex/serviceindex.go
> +	// are no ports specified, it means no ports (thus, not IP set membership). If nil is specified,
typo: not

2021-07-01 10:28 UTC, fasaxc commented on serviceindex/serviceindex.go
> +		panic(fmt.Sprintf("BUG: Same ID generated for two service names: %s and %s", curr.ServiceName, serviceName))
Use `logrus.Panic` because it flushes the log on the way down.

2021-07-23 18:08 UTC, caseydavenport commented on dataplane/windows/policysets/policysets.go
> +	// TODO: Implement match on IP+port IP sets.
Leaving out for now to get this in, but will submit a follow-up shortly after.

2021-07-23 18:10 UTC, caseydavenport commented
@fasaxc I believe I've got all the necessary tests covered now! Could you give this a second look?

2021-07-26 09:16 UTC, fasaxc requested changes
Looking good; just a couple of points:
* I do like to have the odd test in the calc graph FV framework since they do cover a lot of the invariants of the calc graph that are tricky to test elsewhere.
* As you flagged, CI is failing.

2021-07-26 09:16 UTC, fasaxc commented on fv/service_policy_test.go
> +		// Traffic the other direciton, and to other ports should be allowed.
Typo: direciton

2021-07-26 18:43 UTC, merged