XDP UT test cases
projectcalico/felix pull request #2944
Opened 2021-08-02 15:43 UTC by mazdakn

## Description

## Todos
- [ ] Unit tests (full coverage)
- [ ] Integration tests (delete as appropriate) In plan/Not needed/Done
- [ ] Documentation
- [ ] Backport
- [ ] Release note

## Release Note

```release-note
None required
```

2021-08-04 16:11 UTC, neiljerram requested changes
Just a couple of things, plus wondering if we can add dest IP cases now?

2021-08-04 16:11 UTC, neiljerram commented on bpf/ut/xdp_test.go
> +// TODO: Add some test cases to match destination IP:Port
Can we do this now?

2021-08-04 17:42 UTC, mazdakn commented on bpf/ut/xdp_test.go
> +// Copyright (c) 2019-2021 Tigera, Inc. All rights reserved.
right, justed pasted it from another file. Will fix it.

2021-08-04 17:43 UTC, mazdakn commented on bpf/ut/xdp_test.go
> +// TODO: Add some test cases to match destination IP:Port
Will check it.

2021-08-05 08:21 UTC, mazdakn commented on bpf/ut/xdp_test.go
> +// TODO: Add some test cases to match destination IP:Port
it works.

2021-08-05 09:01 UTC, neiljerram approved these changes
LGTM, thanks!

2021-08-05 10:41 UTC, merged